<?php
/**
 * Template: Seznam zákazníků - SIMPLIFIED with Data Table System
 * 
 * All logic is now in SAW_Data_Table and SAW_Customers_Controller.
 * This template is now automatically generated by the controller.
 * 
 * @package SAW_Visitors
 * @version 4.6.1
 */

if (!defined('ABSPATH')) {
    exit;
}

// This file is now just a placeholder.
// The actual rendering happens in SAW_Customers_Controller::index()
// using the SAW_Data_Table system.

// If you need to include this template directly, use:
// echo SAW_App_Layout::render('customers/list', $data);